name: CI Checks

on:
  push:
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./geras

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./geras/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Expo Lint
        run: npm run lint

      - name: Check Prettier Formatting
        run: npm run check-format

      - name: Create .env file
        run: echo "API_KEY=${{ secrets.API_KEY }}" > .env
